config/routes.rb
Rails.application.routes.draw do
  resources :users, :tasks
  resources :login, :only => [:create, :new, :destroy]


  #Need to add route to home page here
  root 'tasks#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :submitted_task, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :tasks
  validates :username, :password_digest, :email, presence: true
  validates :username, :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsConcern
  protect_from_forgery with: :exception
end

app/controllers/concerns/session.rb
module SessionHelper
  def session_logged_in?
    !session[:current_user_id].nil?
  end

  def session_user
    begin
      @current_user ||= User.find(session[:current_user_id])
    rescue ActiveRecord::RecordNotFound => e
      session.clear
      @current_user = nil
    end
  end

  def session_logout
    session.clear
  end

  def session_login user
    session[:current_user_id] = user.id
  end
end

app/controllers/concerns/sessions_concern.rb
require 'active_support/concern'
module SessionsConcern
  extend ActiveSupport::Concern

  def session_logged_in?
    !session[:current_user_id].nil?
  end

  def session_user
    begin
      @current_user ||= User.find(session[:current_user_id])
    rescue ActiveRecord::RecordNotFound => e
      session.clear
      @current_user = nil
    end
  end

  def session_logout
    session.clear
  end

  def session_login user
    session[:current_user_id] = user.id
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by(email: params[:login][:email])
    if @user && @user.authenticate(params[:login][:password_digest])
      session_login @user
      redirect_to root_url
    else
      flash[:notice] = "Invalid Email/Password Combination"
      redirect_to new_login_path
    end
  end

  def destroy
    session_logout
    redirect_to root_url
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    if request.xhr?
      @task.save
      render json: @task
    else
      redirect_to root_path
    end
  end

  def new
    @task = Task.new
    render :new
  end

  def index
    @task = Task.new
    @user_tasks = session_logged_in? ? Task.where(user_id:  session_user.id).last(10) : nil
    @update_user_path = session_logged_in? ? "/users/#{session_user.id}" : ""
    render :index
  end

  def update
    task_id = params[:id].to_i
    task = Task.find(task_id)
    Task.update(task_id, :completed => !task.completed)
    task = Task.find(task_id)
    if request.xhr?
      render json: task.completed
    else
      redirect_to root_path
    end
  end

  private
    def task_params
      params.require(:task).permit(:user_id, :submitted_task)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def create
    @user = User.new(user_params)
    @user.password = user_params[:password_digest]
    @user.timer_count = 0
      if @user.save
        session_login @user
        redirect_to root_url
      else
        @user.errors.full_messages
        render :new
      end
  end

  def update
    @user = User.find(params[:id])
    p @user
    if request.xhr?
      @user.timer_count += 1
      @user.save
    else
      redirect_to root_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password_digest, :encrypted_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def session_logged_in?
    !session[:current_user_id].nil?
  end

  def session_user
    begin
      @current_user ||= User.find(session[:current_user_id])
    rescue ActiveRecord::RecordNotFound => e
      session.clear
      @current_user = nil
    end
  end

  def session_logout
    session.clear
  end

  def session_login user
    session[:current_user_id] = user.id
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timer and Tasks</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-static-top navbar-default">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          <% if session_logged_in? %>
            <li><%= link_to "#{session_user.username}", user_path(session_user) %></li>
            <li><%= link_to "Logout", login_path(session_user.id), :method => :delete %></li>
          <% else %>
            <li><%=link_to 'Register', new_user_path %></li>
            <li><%=link_to 'Login', new_login_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <h1>Timer and Tasks</h1>

    <%= yield %>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </body>
</html>

app/views/login/new.html.erb
<div class="row">
  <div class="col-md-3 col-md-offset-3">
    <%= flash[:notice] %>
    <%= form_for :login,  url: {action: "create"} do |f| %>
      <%= f.label "Email" %>
      <%= f.email_field :email, :class => 'form-control' %></br>
      <%= f.label "Password" %>
      <%= f.password_field :password_digest, :class => 'form-control' %></br>
      <%= f.submit :class => "btn btn-default", value: "Log In"%>
    <% end %>
  </div>
</div>

app/views/tasks/_new.html.erb
<%= form_for @task, url: {action: "create"} do |f| %>
  <%= f.hidden_field :user_id, value: session_user.id %>
  <%= f.text_field :submitted_task, placeholder: "New task", required: true %>
  <input type="submit" value="Create Task"/>
<% end %>

app/views/tasks/index.html.erb
<div id="countdown" data-update-url="<%= @update_user_path %>"></div>
<audio id="audio" src="https://www.soundjay.com/clock/alarm-clock-01.mp3" autostart="false" ></audio>
<div id="timer-buttons">
  <i class="fa btn fa-backward fa-2x timer-btn" id="reset-btn" aria-hidden="true"></i>
  <i class="fa btn fa-play fa-2x timer-btn" id="start-btn" aria-hidden="true"></i>
  <i class="fa btn fa-pause fa-2x timer-btn" id="pause-btn" aria-hidden="true"></i>
  <i class="fa btn fa-play fa-2x timer-btn" id="resume-btn" aria-hidden="true"></i>
</div>

<% if session_logged_in?%>
  <div class="list-container">
    <h3>My  Tasks</h3>
    <%= render "tasks/new" %>
    <ul class="task-list-group">
      <% @user_tasks.each do |task| %>
        <% if task.completed %>
          <a class="task-list-item task-item-complete" data-task-id="<%= task.id %>"><%= task["submitted_task"] %></a>
        <% else %>
          <a class="task-list-item task-item-incomplete" data-task-id="<%= task.id %>"><%= task["submitted_task"] %></a>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<section class="errors">
  <ul>
    <% @user.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
</section>
  <div class="row">
    <div class="col-md-3 col-md-offset-3">
      <%= form_for [@user] do |f| %>
        <%= f.label "Username" %>
        <%= f.text_field :username, :class => 'form-control' %>
        <%= f.label "Email" %>
        <%= f.email_field :email, :class => 'form-control'%>
        <%= f.label "Password" %>
        <%= f.password_field :password_digest, :class => 'form-control' %>
        <%= f.submit :class => "btn btn-default", value: "Sign Up" %>
        <%= flash[:notice] %>
      <% end %>
    </div>
  </div>

app/views/users/show.html.erb
<% if session_logged_in? %>
  <h2><%= "#{session_user.username}'s Profile" %></h2>
  <%= "Sign Up Date: #{(session_user.created_at).to_date.to_formatted_s(:long)}" %> </br>
  <%= "Total Completed Timers: #{session_user.timer_count}" %>
  <h3>My Tasks</h3>
  <ul class="task-list-group">
    <% Task.where(user_id: session_user.id).each do |task| %>
      <a class="task-list-item false-link" data-task-id="<%= task.id %>"><%= task.submitted_task %><br><br><%= task.created_at.to_date.to_formatted_s(:long) %></a>
    <% end %>
  </ul>
<% else %>
  <%= "You need to be logged in to see this page" %>
<% end %>